#!/bin/sh -l

sh -c "echo KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT KILL OCTOCAT "
